version: '3'

tasks:

  migrate-up:
    desc: "create database tables"
    dir: ./auth
    cmds:
      - go run ./cmd/migrator --storage-path=./internal/storage/auth.sqlite --migration-path=./migrations up

  migrate-down:
    desc: "delete database tables"
    dir: ./auth
    cmds:
      - go run ./cmd/migrator --storage-path=./internal/storage/auth.sqlite --migration-path=./migrations down

  run-server:
    desc: "Run auth server"
    dir: ./auth
    cmds:
      - go run ./cmd/main.go --config_path=./config/prod.yaml

  run-client:
    desc: "Run auth client"
    dir: ./client
    cmds:
      - go run ./cmd/main.go
